name: avh4-lib
version: 0.0.0.1

synopsis: Common code for haskell projects
license: BSD-3-Clause
license-file: LICENSE
author: Aaron VonderHaar
maintainer: gruen0aermel@gmail.com
copyright: See https://github.com/avh4/elm-format/blob/master/LICENSE

build-type: Simple

language: Haskell2010

default-extensions:
  - DeriveFunctor
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - ScopedTypeVariables

ghc-options:
  - -O2
  - -Wall
  - -Wno-name-shadowing

dependencies:
  ansi-terminal: ">= 0.11 && < 0.12"
  ansi-wl-pprint: ">= 0.6.9 && < 0.7"
  array: ">= 0.5.4.0 && < 0.6"
  base: ">= 4.15.0.0 && < 5"
  bimap: ">= 0.4.0 && < 0.6"
  binary: ">= 0.8.9.0 && < 0.9"
  bytestring: ">= 0.11.3.0 && < 0.12"
  containers: ">= 0.6.5.1 && < 0.7"
  directory: ">= 1.3.6.2 && < 2"
  deepseq: ">= 1.4.8.1 && < 2"
  filepath: ">= 1.4.2.1 && < 2"
  mtl: ">= 2.2.2 && < 3"
  pooled-io: ">= 0.0.2 && < 0.1"
  process: ">= 1.6.13.2 && < 2"
  text: ">= 2.0 && < 3"
  transformers: "0.6.1.0 && < 0.7"

library:
  source-dirs:
    - src

tests:
  al-tests:
    main: Tests.hs
    source-dirs:
      - test
      - src

    dependencies:
      tasty: ">= 1.2 && < 2"
      tasty-hspec: ">= 1.2.0.3 && < 1.3"
      tasty-hunit: ">= 0.10.0.1 && < 0.11"

    build-tools:
      tasty-discover: ">= 4.2.1 && < 5"
